export const SET_DASHBOARD_GREETINGS = 'SET_DASHBOARD_GREETINGS';
export const ADD_CANCEL_REQUEST = 'ADD_CANCEL_REQUEST';

export const GET_DASHBOARD_GREETINGS = 'GET_DASHBOARD_GREETINGS';
export const SET_ASIDE_NAV_MODE = 'SET_ASIDE_NAV_MODE';

export const FETCH_WEATHER = 'FETCH_WEATHER';
export const RESOLVE_WEATHER = 'RESOLVE_WEATHER';
